apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-init
data:
  init-mongo.js: |
    db = db.getSiblingDB('shoppinglist');
    db.createCollection('shoppinglists');
    db.createCollection('shoppingitems');
