apiVersion: v1
kind: Service
metadata:
  name: shoppinglist-api-service
spec:
  selector:
    app: shoppinglist-api
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
  type: NodePort
