apiVersion: apps/v1
kind: Deployment
metadata:
  name: shoppinglist-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shoppinglist-service
  template:
    metadata:
      labels:
        app: shoppinglist-service
    spec:
      containers:
      - name: shoppinglist-service
        image: kdkanishka/shoppinglist-service:0.3
        ports:
        - containerPort: 8080
        env:
        - name: MONGO_URI
          value: "mongodb://mongodb:27017"